Models/ApplicationContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace EventRegistration.Models
{
    public class ApplicationContext : DbContext
    {
        public DbSet<UserEventRegistration> UserEventRegistrations { get; set; }

        public ApplicationContext(DbContextOptions<ApplicationContext> options)
            : base(options)
        {
            //Database.EnsureCreated();   // создаем базу данных при первом обращении
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace EventRegistration.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserEventRegistration.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EventRegistration.Models
{
    public class UserEventRegistration
    {
        [Key]
        public int ID { get; set; }
        public string Email { get; set; }
        public string Group { get; set; }
        public string UniversityGraduationDate { get; set; }
        public string Description { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }

        public long DateRegistraion { get; set; }
        public bool StatusRegistration { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EventRegistration.Models;
using Newtonsoft.Json.Linq;

namespace EventRegistration.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationContext applicationContext;

        public HomeController (ApplicationContext application)
        {
            applicationContext = application;
        }

        public IActionResult Index()
        {
            //Проверить пользователя на регистрацию по куки, если она уже была то перекинуть, а если не была, то на сайт для регистрации
            return View();
        }

        [HttpPost]
        public async Task<JObject> UserRegistrationAsync(UserEventRegistration user)
        {
            JObject j = new JObject();

            applicationContext.Add(user);

            await applicationContext.SaveChangesAsync();

            return j;
        }

    }
}

Controllers/UserEventController.cs
using ClosedXML.Excel;
using EventRegistration.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EventRegistration.Controllers
{
    public class UserEventController : Controller
    {
        private readonly ApplicationContext _context;

        public UserEventController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: UserEvent
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserEventRegistrations.ToListAsync());
        }

        // GET: UserEvent/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEventRegistration = await _context.UserEventRegistrations
                .FirstOrDefaultAsync(m => m.ID == id);
            if (userEventRegistration == null)
            {
                return NotFound();
            }

            return View(userEventRegistration);
        }

        // GET: UserEvent/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserEvent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Email,Group,UniversityGraduationDate,Description,FullName,Phone,DateRegistraion,StatusRegistration")] UserEventRegistration userEventRegistration)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userEventRegistration);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userEventRegistration);
        }

        // GET: UserEvent/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEventRegistration = await _context.UserEventRegistrations.FindAsync(id);
            if (userEventRegistration == null)
            {
                return NotFound();
            }
            return View(userEventRegistration);
        }

        // POST: UserEvent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Email,Group,UniversityGraduationDate,Description,FullName,Phone,DateRegistraion,StatusRegistration")] UserEventRegistration userEventRegistration)
        {
            if (id != userEventRegistration.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userEventRegistration);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserEventRegistrationExists(userEventRegistration.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userEventRegistration);
        }

        // GET: UserEvent/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userEventRegistration = await _context.UserEventRegistrations
                .FirstOrDefaultAsync(m => m.ID == id);
            if (userEventRegistration == null)
            {
                return NotFound();
            }

            return View(userEventRegistration);
        }

        // POST: UserEvent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userEventRegistration = await _context.UserEventRegistrations.FindAsync(id);
            _context.UserEventRegistrations.Remove(userEventRegistration);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserEventRegistrationExists(int id)
        {
            return _context.UserEventRegistrations.Any(e => e.ID == id);
        }

        [HttpPost]
        public FileResult Export()
        {
            DataTable dt = getData();
            //Name of File  
            string fileName = "Sample.xlsx";
            using (XLWorkbook wb = new XLWorkbook())
            {
                //Add DataTable in worksheet  
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    //Return xlsx Excel File  
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                }
            }
        }

        public DataTable getData()
        {
            //Creating DataTable  
            DataTable dt = new DataTable();
            //Setiing Table Name  
            dt.TableName = "EmployeeData";
            //Add Columns  
            dt.Columns.Add("ID", typeof(int));
            dt.Columns.Add("Name", typeof(string));
            dt.Columns.Add("City", typeof(string));
            //Add Rows in DataTable  
            dt.Rows.Add(1, "Anoop Kumar Sharma", "Delhi");
            dt.Rows.Add(2, "Andrew", "U.P.");
            dt.AcceptChanges();
            return dt;
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model UserEventRegistration
@{
    ViewData["Title"] = "Регистрация на событие";
}


<form asp-action="UserRegistration" asp-controller="home">
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="ma" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Group" class="control-label">Группа</label>
        <input type="text" asp-for="Group" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="UniversityGraduationDate" class="control-label">Дата окончания университета</label>
        <input type="text" asp-for="UniversityGraduationDate" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание ХЗ</label>
        <input type="text" asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="FullName" class="control-label">Полное имя и фамилия</label>
        <input type="text" asp-for="FullName" class="form-control" />
    </div>
        <div class="form-group">
        <label asp-for="Phone" class="control-label">Телефон</label>
        <input type="text" asp-for="Phone" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventRegistration</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EventRegistration</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="UserEvent" asp-action="Index">About</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - EventRegistration</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/UserEvent/Create.cshtml
@model EventRegistration.Models.UserEventRegistration

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>UserEventRegistration</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversityGraduationDate" class="control-label"></label>
                <input asp-for="UniversityGraduationDate" class="form-control" />
                <span asp-validation-for="UniversityGraduationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateRegistraion" class="control-label"></label>
                <input asp-for="DateRegistraion" class="form-control" />
                <span asp-validation-for="DateRegistraion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="StatusRegistration" /> @Html.DisplayNameFor(model => model.StatusRegistration)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserEvent/Delete.cshtml
@model EventRegistration.Models.UserEventRegistration

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserEventRegistration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UniversityGraduationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UniversityGraduationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateRegistraion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateRegistraion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StatusRegistration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusRegistration)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/UserEvent/Details.cshtml
@model EventRegistration.Models.UserEventRegistration

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserEventRegistration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UniversityGraduationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UniversityGraduationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateRegistraion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateRegistraion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StatusRegistration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StatusRegistration)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/UserEvent/Edit.cshtml
@model EventRegistration.Models.UserEventRegistration

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>UserEventRegistration</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversityGraduationDate" class="control-label"></label>
                <input asp-for="UniversityGraduationDate" class="form-control" />
                <span asp-validation-for="UniversityGraduationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateRegistraion" class="control-label"></label>
                <input asp-for="DateRegistraion" class="form-control" />
                <span asp-validation-for="DateRegistraion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="StatusRegistration" /> @Html.DisplayNameFor(model => model.StatusRegistration)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserEvent/Index.cshtml
@model IEnumerable<EventRegistration.Models.UserEventRegistration>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniversityGraduationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateRegistraion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusRegistration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Group)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UniversityGraduationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateRegistraion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusRegistration)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@using (Html.BeginForm("Export", "UserEvent", FormMethod.Post))
{
    <input type="submit" value="Export to Excel" class="button" />
}